### PR TITLE
Close iterator from reader properly

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by ccaominh** [comment]
Looks like we're missing the snapshots repo, so CI keeps failing.

```
<repoOrgId>apache.snapshots</repoOrgId>
<repoOrgName>Apache Snapshot Repository</repoOrgName>
<repoOrgUrl>https://repository.apache.org/snapshots</repoOrgUrl>

<repositories>
    <repository>
        <id>${repoOrgId}</id>
        <name>${repoOrgName}</name>
        <url>${repoOrgUrl}</url>
    </repository>
</repositories>
```

**Comment by jihoonson** [comment]
Yeah, I'm not sure what to do though. @suneet-s can we use the latest tag of 0.18.0-iap?

**Comment by suneet-s** [comment]
> Looks like we're missing the snapshots repo, so CI keeps failing.
> 
> ```
> <repoOrgId>apache.snapshots</repoOrgId>
> <repoOrgName>Apache Snapshot Repository</repoOrgName>
> <repoOrgUrl>https://repository.apache.org/snapshots</repoOrgUrl>
> 
> <repositories>
>     <repository>
>         <id>${repoOrgId}</id>
>         <name>${repoOrgName}</name>
>         <url>${repoOrgUrl}</url>
>     </repository>
> </repositories>
> ```

There is a snapshots repo 🤯

**Comment by suneet-s** [comment]
The latest iap tag won't work either because we don't publish them anywhere AFAICT

It looks like the last druid version published in the apache snapshots repo is 0.13

**Comment by jihoonson** [comment]
Yeah that's true, but I think that's the right way to go. In fact, I think all our extensions should depend on Imply distribution, not ASF one. As we talked in the meeting today, we are going to publish Imply artifacts to our own maven repo.

**Comment by jihoonson** [comment]
For note, [seems like we can use GitHub Packages as a maven repo](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages).

**Pull request closed without merging**
